---
- name: Package Installation
  hosts: all
  become: true
  tasks:

    - name: Installing HTTPD package
      dnf:
        name: httpd
        state: latest

    - name: Start HTTPD service
      service:
        name: httpd
        state: started
        enabled: true
